//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class UsersReg
    {
        public int User_id { get; set; }

		[Required(ErrorMessage = "Required.")]
		public string Username { get; set; }

		[Required(ErrorMessage = "Required.")]
		public string Password { get; set; }

		[Required(ErrorMessage = "Required.")]
		[EmailAddress(ErrorMessage = "Invalid email address.")]
		public string Email { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }

        public Nullable<System.DateTime> LastLoginDate { get; set; }
		public bool RememberMe { get; internal set; }
	}
}
